[project]
name = "ug-calendar-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daste", email = "stefankar1000@gmail.com" }
]
requires-python = ">=3.14"

dependencies = [
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "ty>=0.0.84",
]

[project.scripts]
ug-calendar-exporter = "ug_calendar_exporter:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
